In [2]:
import pandas as pd
df = pd.read_csv('../data/raw/scraped_tweets-2022-11-25 13:08:18.129252-2022-11-26 13:08:18.129252.csv', lineterminator='\n')
print(df.shape)
df.dropna(subset=['id'], inplace=True)
df.reset_index(drop=True, inplace=True)
print(df.shape)
df

(10800, 12)
(10800, 12)

,id,text,create_at,geo,retweet_count,like_count,hashtags,username,following,followers,user_total_tweets,user_likes_count
0,1596292594451070976,#Binance has allocated an additional $1 billio...,2022-11-25 23:59:46+00:00,NaN,0,1,#ftx,the_artofchart,185,2311,3201,528
1,1596292551035584512,REPORT: Mexican unicorn #Bitso sets out transp...,2022-11-25 23:59:36+00:00,$COOKIES TO THE MOON 🤩🤩,1848,0,#ftx,enjenieeei,3152,450,85691,11578
2,1596292423134707714,#Cro #FTT #CryptoCom #GOX https://t.co/tdIokXH...,2022-11-25 23:59:06+00:00,NaN,0,0,#ftx,Dianac647422,15,3,28,0
3,1596292404671569921,REPORT: Mexican unicorn #Bitso sets out transp...,2022-11-25 23:59:01+00:00,"Jakarta Selatan, DKI Jakarta",1848,0,#ftx,gavinadingJr,3207,50,10234,1891
4,1596292316272418816,Get out of #WBTC NOW!!! \n\nTurns out half of ...,2022-11-25 23:58:40+00:00,NaN,616,0,#ftx,KoreaynYongnam,3653,224,12718,1180
...,...,...,...,...,...,...,...,...,...,...,...,...
10795,1596273629699796992,It’s your daily reminder that for the last 9 m...,2022-11-25 22:44:25+00:00,"Vilnius, Lithuania",1333,0,#ukraine,WeLoveYouUA,64,52,1951,24898
10796,1596273627258765312,#Ukraine: A disabled Russian tank was destroye...,2022-11-25 22:44:24+00:00,Ελλάς,246,0,#ukraine,LoukGeorgiadis,18120,16823,136072,363301
10797,1596273601250226179,"""It's easy to run a marathon when you know how...",2022-11-25 22:44:18+00:00,"Toronto, Ontario, Canada",85,0,#ukraine,PaulSweeneyYYZ,1005,2321,262725,231996
10798,1596273600406999042,The #EU is going to provide #Ukraine with 200 ...,2022-11-25 22:44:18+00:00,"Dublin, Ireland",158,0,#ukraine,Le_Sian,4992,1223,112208,123935
10799,1596273599026933760,#Ukraine: The victims of Ukrainian counter-bat...,2022-11-25 22:44:17+00:00,Ελλάς,503,0,#ukraine,LoukGeorgiadis,18120,16823,136072,363301

In [11]:
df.hashtags.unique()

array(['#ftx', '#vegan', '#climatechange', '#christmas', '#covid',
       '#ukraine'], dtype=object)

In [12]:
max(df['create_at'])

'2022-11-25 23:59:59+00:00'

In [13]:
min(df['create_at'])

'2022-11-25 14:41:34+00:00'

In [14]:
df.to_csv('data/scraped_tweets-posted-11-25-collected-12-02.csv', index=False)

In [5]:
import glob
import pandas as pd
results = glob.glob('../data/*.csv')
df = pd.DataFrame()
for path in results:
    if path == "../data/scraped_tweets-posted-11-09-collected-11-16.csv" or path == "../data/scraped_tweets-posted-11-25-collected-12-02.csv":
        continue
    tmp = pd.read_csv(path, lineterminator='\n')
    print(tmp.shape)
    df = pd.concat([df, tmp])
df = df[df['hashtags'] != '#lgbtq#nft']
df.dropna(subset=['hashtags'], inplace=True, axis=0)
df

(10613, 12)
(9889, 12)
(10493, 12)
(10800, 12)
(10800, 12)
(10800, 12)
(10800, 12)
(9002, 12)
(10800, 12)
(10990, 12)
(10800, 12)
(10800, 12)
(10800, 12)
(10800, 12)
(10451, 12)

,id,text,create_at,geo,retweet_count,like_count,hashtags,username,following,followers,user_total_tweets,user_likes_count
0,1.591219e+18,'Like a 1930s Dictator': Vitalik Buterin Lays ...,2022-11-11 23:59:59+00:00,"For now, Earth",0.0,1.0,#ftx,johnmorganFL,630.0,28492.0,240872.0,111.0
1,1.591219e+18,"💸 $1,000 #Giveaway 💸\n\nWe'll select 10 winner...",2022-11-11 23:59:57+00:00,Panama,8866.0,0.0,#ftx,KuKzNFT,594.0,1014.0,4452.0,8272.0
2,1.591219e+18,#FTX crazy Shit! #Crypto https://t.co/2GO4X3u2pt,2022-11-11 23:59:55+00:00,"Seattle, WA",0.0,0.0,#ftx,MeAndMySports,315.0,342.0,3032.0,1572.0
3,1.591219e+18,"Yo @SBF_FTX, draw me like one of your French g...",2022-11-11 23:59:53+00:00,"London, England",0.0,0.0,#ftx,thedoc7er,1513.0,296.0,4541.0,3626.0
4,1.591219e+18,@BitcoinMagazine you you simpletons cant under...,2022-11-11 23:59:51+00:00,NaN,0.0,1.0,#ftx,jesseypaul4,123.0,44.0,317.0,81.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10446,1.591565e+18,"🔴 WAR IN 🇺🇦: FRANCE 24 reporter @cntrentF24, w...",2022-11-12 22:52:11+00:00,Hauts de France 🇫🇷 🇪🇺,20.0,0.0,#ukraine,annetteashley61,10522.0,9603.0,437088.0,291392.0
10447,1.591565e+18,People still celebrating in Kherson and I love...,2022-11-12 22:52:09+00:00,"Belgrade, Serbia, Europe",1041.0,0.0,#ukraine,svrhovac,222.0,150.0,9174.0,16675.0
10448,1.591565e+18,A remarkable story #Ukraine https://t.co/eeBLc...,2022-11-12 22:52:04+00:00,Guernsey,0.0,0.0,#ukraine,TimBarker10,2668.0,1217.0,3290.0,5927.0
10449,1.591565e+18,#Ukraine: Relief in liberated #Kherson after 8...,2022-11-12 22:52:02+00:00,🇮🇪🇪🇺🇺🇦🎮,189.0,0.0,#ukraine,Aontaithe2021,5001.0,2376.0,392315.0,308109.0
10450,1.591564e+18,Drone Drops Grenade Directly on Russian Soldie...,2022-11-12 22:51:59+00:00,NaN,0.0,0.0,#ukraine,vbl68,28.0,16.0,2760.0,21.0

In [6]:
# Functions for preprocessing texts
import nltk
from nltk.metrics.distance import jaccard_distance, edit_distance
from nltk.util import ngrams
nltk.download('words')
nltk.download('stopwords')
nltk.download('punkt')
import re

def clean_text(text):
  # remove new lines and tab spaces
  text = text.replace('\n',' ')
  text = text.replace('\t',' ')
  # remove mentions and urls
  text = re.sub(r"(?:\@|https?\://)\S+", "", text)
  text = text.lower()
  # remove punctuation and emojis
  text = re.sub(r'[^\w\s#]', '', text)
  emoji_pattern = re.compile("["
          u"\U0001F600-\U0001F64F"  # emoticons
          u"\U0001F300-\U0001F5FF"  # symbols & pictographs
          u"\U0001F680-\U0001F6FF"  # transport & map symbols
          u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                            "]+", flags=re.UNICODE)
  text = text.encode('utf-8', errors='ignore').decode('utf-8') # remove non utf-8
  text = re.sub(r'\d+', '', text) # remove numbers
  text = emoji_pattern.sub(r'', text) # no emoji
  return text


from gensim.parsing.preprocessing import remove_stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk_stopwords = set(stopwords.words('english'))
def remove_stop_words(text):
  # remove stop words
  text = remove_stopwords(text) #gensim method
  text_tokens = word_tokenize(text)
  text_tokens = [word for word in text_tokens if not word in nltk_stopwords] #nltk method
  text = ' '.join(text_tokens)
  return text

from textblob import TextBlob
# word correction
def word_correction(text):
  return TextBlob(text).correct()

# lemmatization
import spacy
nlp = spacy.load("en_core_web_sm")
def lemmatize(text):        
    sent = []
    doc = nlp(text)
    for word in doc:
        if len(word) < 3:
          continue
        if '@' in word.text:  # these are hashtags and should be left unaltered
          sent.append(word.text)
        else:
          sent.append(word.lemma_)
    text =  " ".join(sent)
    return text.replace('-PRON-', '')

[nltk_data] Downloading package words to /home/lyuxiao/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/lyuxiao/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/lyuxiao/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [10]:
sample_text = '@Sam #web3 #FTX #FTT #binance #Metaverse #Airdrop #tokens #moon #airdrops #airdrop #freeairdrop #getfree #free https://t.co/UfHNIYobpj caltural'

cleaned_text = clean_text(sample_text)
cleaned_text = lemmatize(cleaned_text.replace('#','@')) #converting # to @ for lemmatizer to leave the hashtags unaltered
cleaned_text = remove_stop_words(cleaned_text)
cleaned_text = cleaned_text.replace('@','') #removing the @ symbols and the hashtag terms are retained as individual words
cleaned_text = re.sub(' +', ' ', cleaned_text)
cleaned_text = word_correction(cleaned_text)
print(cleaned_text)

 web fix fat finance metaverse wardrop tokens moon raindrops wardrop freeairdrop getfree free cultural

In [8]:
from tqdm import tqdm
clean_tweets = []

n = len(df.text)
for i in tqdm(range(n)):
    cleaned_text = clean_text(df.text.iloc[i])
    cleaned_text = lemmatize(cleaned_text.replace('#','@')) #converting # to @ for lemmatizer to leave the hashtags unaltered
    cleaned_text = remove_stop_words(cleaned_text)
    cleaned_text = cleaned_text.replace('@','') #removing the @ symbols and the hashtag terms are retained as individual words
    cleaned_text = re.sub(' +', ' ', cleaned_text)
    # cleaned_text = word_correction(cleaned_text)
    clean_tweets.append(cleaned_text)
clean_tweets[:5]

100%|██████████| 157508/157508 [25:36<00:00, 102.54it/s]

['like dictator vitalik buterin lay sam bankmanfrie ftx',
 ' giveaway select winner randomly award account rule tag friend like follow amp retweet good luck btc crypto contest casino xrp competition cryptocurrency ftx nft',
 ' ftx crazy shit crypto',
 'draw like french girl ftxcrash ftx binance czbinance cryptomarket btc sol ftt',
 'simpleton understand crypto wallet like exodus metamask bravewallet people loose money echange celcious voyager blockfi ftx lose money voyager hope hope']

In [9]:
df['cleaned_text'] = clean_tweets
# df.to_csv('data/cleaned.csv.gz', index=False, compression='gzip')

In [10]:
df.to_csv('../data/cleaned.csv.gz', compression='gzip', index=False)